### ISSUE TITLE
Old team names not being treated as correct

### ISSUE THREAD

**Issue by slxmmy999** [slxmmy999/InfiniteBaseballGrid#2]

**Comment by meidlinger** [comment]
I submitted a PR on this topic to add KCA:  https://github.com/slxmmy999/InfiniteImmaculateGrid/pull/14

There are some issues with using team names, however.  Some team names have been recycled a bunch and are separate franchises.  Some examples:

Philadelphia Athletics:
1882-1890  https://www.baseball-reference.com/teams/PHA/
1890-1891  https://www.baseball-reference.com/teams/PHQ/
1901-present OAK (with "modern" PHA and KCA)

Washington Senators:
1891-1899:  https://www.baseball-reference.com/teams/WAS/
1901-present (now MIN):  https://www.baseball-reference.com/teams/MIN/
1961-present (now TEX): https://www.baseball-reference.com/teams/PHQ/

Washington Nationals:
1872-1872:  https://www.baseball-reference.com/teams/NAT/
1875-1875:  https://www.baseball-reference.com/teams/WNT/
1884-1884:  https://www.baseball-reference.com/teams/WNA/
1886-1889:  https://www.baseball-reference.com/teams/WNL/
1969-present:  https://www.baseball-reference.com/teams/WSN/

There may be others, but these are the few that I've come across.  Most are pretty ancient edge cases but the 1961-1971 Senators should go to the Rangers, not the Twins.

If I can find some time, I'm happy to look into this but can't guarantee anything right now.  Thanks for putting this together!

**Comment by slxmmy999** [comment]
Thanks for this! Honestly I just threw together a list of old team names without doing the right research, so I'll get these updated!

**Comment by meidlinger** [comment]
> Thanks for this! Honestly I just threw together a list of old team names without doing the right research, so I'll get these updated!

No prob, I've been enjoying the daily grid and was happy to discover this infinite grid.  If I understand the behavior of the daily grid, stats for defunct franchises are included in career stats but seasonal stats (like 20 wins for the 1872 Nationals) don't.  I'll try to confirm that.

And as for the "right research" -- release early, release often, eh?  People can't help if it isn't out there.  :)
